<?php

/**
 * This is the model base class for the table "tape_reviewer".
 * DO NOT MODIFY THIS FILE! It is automatically generated by AweCrud.
 * If any changes are necessary, you must set or override the required
 * property or method in class "TapeReviewer".
 *
 * Columns in table "tape_reviewer" available as properties of the model,
 * followed by relations of table "tape_reviewer" available as properties of the model.
 *
 * @property integer $id
 * @property string $user_id
 * @property integer $tape_file_id
 * @property string $status
 * @property string $remarks
 *
 * @property TapeFile $tapeFile
 * @property User $user
 */
abstract class BaseTapeReviewer extends AweActiveRecord {

    public static function model($className=__CLASS__) {
        return parent::model($className);
    }

    public function tableName() {
        return 'tape_reviewer';
    }

    public static function representingColumn() {
        return 'tape_file_id';
    }

    public function rules() {
        return array(
            array('user_id, tape_file_id', 'required'),
            array('tape_file_id', 'numerical', 'integerOnly'=>true),
            array('user_id', 'length', 'max'=>11),
            array('status', 'length', 'max'=>128),
            array('remarks', 'length', 'max'=>256),
            array('status, remarks', 'default', 'setOnEmpty' => true, 'value' => null),
            array('id, user_id, tape_file_id, status, remarks', 'safe', 'on'=>'search'),
        );
    }

    public function relations() {
        return array(
            'tapeFile' => array(self::BELONGS_TO, 'TapeFile', 'tape_file_id'),
            'user' => array(self::BELONGS_TO, 'User', 'user_id'),
        );
    }

    /**
     * @return array customized attribute labels (name=>label)
     */
    public function attributeLabels() {
        return array(
                'id' => Yii::t('app', 'ID'),
                'user_id' => Yii::t('app', 'User'),
                'tape_file_id' => Yii::t('app', 'Tape File'),
                'status' => Yii::t('app', 'Status'),
                'remarks' => Yii::t('app', 'Remarks'),
                'tapeFile' => null,
                'user' => null,
        );
    }

    public function search() {
        $criteria = new CDbCriteria;

        $criteria->compare('id', $this->id);
        $criteria->compare('user_id', $this->user_id);
        $criteria->compare('tape_file_id', $this->tape_file_id);
        $criteria->compare('status', $this->status, true);
        $criteria->compare('remarks', $this->remarks, true);

        return new CActiveDataProvider($this, array(
            'criteria' => $criteria,
        ));
    }

    public function behaviors() {
        return array_merge(array(
            'ActiveRecordRelation' => array(
                'class' => 'EActiveRecordRelationBehavior',
            ),
        ), parent::behaviors());
    }
}