<?php

/**
 * This is the model base class for the table "file_upload".
 * DO NOT MODIFY THIS FILE! It is automatically generated by AweCrud.
 * If any changes are necessary, you must set or override the required
 * property or method in class "FileUpload".
 *
 * Columns in table "file_upload" available as properties of the model,
 * and there are no model relations.
 *
 * @property integer $id
 * @property integer $user_id
 * @property string $file_name
 * @property integer $file_size
 * @property string $remarks
 *
 */
abstract class BaseFileUpload extends AweActiveRecord {

    public static function model($className=__CLASS__) {
        return parent::model($className);
    }

    public function tableName() {
        return 'file_upload';
    }

    public static function representingColumn() {
        return 'file_name';
    }

    public function rules() {
        return array(
            array('user_id, file_name, file_size, remarks', 'required'),
            array('user_id, file_size', 'numerical', 'integerOnly'=>true),
            array('file_name', 'length', 'max'=>256),
            array('remarks', 'length', 'max'=>512),
            array('id, user_id, file_name, file_size, remarks', 'safe', 'on'=>'search'),
        );
    }

    public function relations() {
        return array(
        );
    }

    /**
     * @return array customized attribute labels (name=>label)
     */
    public function attributeLabels() {
        return array(
                'id' => Yii::t('app', 'ID'),
                'user_id' => Yii::t('app', 'User'),
                'file_name' => Yii::t('app', 'File Name'),
                'file_size' => Yii::t('app', 'File Size'),
                'remarks' => Yii::t('app', 'Remarks'),
        );
    }

    public function search() {
        $criteria = new CDbCriteria;

        $criteria->compare('id', $this->id);
        $criteria->compare('user_id', $this->user_id);
        $criteria->compare('file_name', $this->file_name, true);
        $criteria->compare('file_size', $this->file_size);
        $criteria->compare('remarks', $this->remarks, true);

        return new CActiveDataProvider($this, array(
            'criteria' => $criteria,
        ));
    }

    public function behaviors() {
        return array_merge(array(
        ), parent::behaviors());
    }
}