<?php

/**
 * This is the model base class for the table "review_feedback".
 * DO NOT MODIFY THIS FILE! It is automatically generated by AweCrud.
 * If any changes are necessary, you must set or override the required
 * property or method in class "ReviewFeedback".
 *
 * Columns in table "review_feedback" available as properties of the model,
 * followed by relations of table "review_feedback" available as properties of the model.
 *
 * @property integer $id
 * @property integer $tape_reviewer_id
 * @property string $start_time
 * @property string $end_time
 * @property string $problem_type
 * @property string $description
 * @property string $status
 * @property string $eval_status
 * @property string $eval_comment
 * @property string $remarks
 * @property string $extra
 *
 * @property TapeReviewer $tapeReviewer
 */
abstract class BaseReviewFeedback extends AweActiveRecord {

    public static function model($className=__CLASS__) {
        return parent::model($className);
    }

    public function tableName() {
        return 'review_feedback';
    }

    public static function representingColumn() {
        return 'start_time';
    }

    public function rules() {
        return array(
            array('tape_reviewer_id, start_time, problem_type, description', 'required'),
            array('tape_reviewer_id', 'numerical', 'integerOnly'=>true),
            array('problem_type, eval_status, extra', 'length', 'max'=>128),
            array('description, remarks', 'length', 'max'=>512),
            array('status', 'length', 'max'=>64),
            array('eval_comment', 'length', 'max'=>256),
            array('end_time', 'safe'),
            array('end_time, status, eval_status, eval_comment, remarks, extra', 'default', 'setOnEmpty' => true, 'value' => null),
            array('id, tape_reviewer_id, start_time, end_time, problem_type, description, status, eval_status, eval_comment, remarks, extra', 'safe', 'on'=>'search'),
        );
    }

    public function relations() {
        return array(
            'tapeReviewer' => array(self::BELONGS_TO, 'TapeReviewer', 'tape_reviewer_id'),
        );
    }

    /**
     * @return array customized attribute labels (name=>label)
     */
    public function attributeLabels() {
        return array(
                'id' => Yii::t('app', 'ID'),
                'tape_reviewer_id' => Yii::t('app', 'Tape Reviewer'),
                'start_time' => Yii::t('app', 'Start Time'),
                'end_time' => Yii::t('app', 'End Time'),
                'problem_type' => Yii::t('app', 'Problem Type'),
                'description' => Yii::t('app', 'Description'),
                'status' => Yii::t('app', 'Status'),
                'eval_status' => Yii::t('app', 'Eval Status'),
                'eval_comment' => Yii::t('app', 'Eval Comment'),
                'remarks' => Yii::t('app', 'Remarks'),
                'extra' => Yii::t('app', 'Extra'),
                'tapeReviewer' => null,
        );
    }

    public function search() {
        $criteria = new CDbCriteria;

        $criteria->compare('id', $this->id);
        $criteria->compare('tape_reviewer_id', $this->tape_reviewer_id);
        $criteria->compare('start_time', $this->start_time, true);
        $criteria->compare('end_time', $this->end_time, true);
        $criteria->compare('problem_type', $this->problem_type, true);
        $criteria->compare('description', $this->description, true);
        $criteria->compare('status', $this->status, true);
        $criteria->compare('eval_status', $this->eval_status, true);
        $criteria->compare('eval_comment', $this->eval_comment, true);
        $criteria->compare('remarks', $this->remarks, true);
        $criteria->compare('extra', $this->extra, true);

        return new CActiveDataProvider($this, array(
            'criteria' => $criteria,
        ));
    }

    public function behaviors() {
        return array_merge(array(
            'ActiveRecordRelation' => array(
                'class' => 'EActiveRecordRelationBehavior',
            ),
        ), parent::behaviors());
    }
}