<?php

/**
 * This is the model base class for the table "cassette_set".
 * DO NOT MODIFY THIS FILE! It is automatically generated by AweCrud.
 * If any changes are necessary, you must set or override the required
 * property or method in class "CassetteSet".
 *
 * Columns in table "cassette_set" available as properties of the model,
 * and there are no model relations.
 *
 * @property integer $id
 * @property string $set_name
 * @property integer $no_of_cassettes
 *
 */
abstract class BaseCassetteSet extends AweActiveRecord {

    public static function model($className=__CLASS__) {
        return parent::model($className);
    }

    public function tableName() {
        return 'cassette_set';
    }

    public static function representingColumn() {
        return 'set_name';
    }

    public function rules() {
        return array(
            array('set_name, no_of_cassettes', 'required'),
            array('no_of_cassettes', 'numerical', 'integerOnly'=>true),
            array('set_name', 'length', 'max'=>128),
            array('id, set_name, no_of_cassettes', 'safe', 'on'=>'search'),
        );
    }

    public function relations() {
        return array(
        );
    }

    /**
     * @return array customized attribute labels (name=>label)
     */
    public function attributeLabels() {
        return array(
                'id' => Yii::t('app', 'ID'),
                'set_name' => Yii::t('app', 'Set Name'),
                'no_of_cassettes' => Yii::t('app', 'No Of Cassettes'),
        );
    }

    public function search() {
        $criteria = new CDbCriteria;

        $criteria->compare('id', $this->id);
        $criteria->compare('set_name', $this->set_name, true);
        $criteria->compare('no_of_cassettes', $this->no_of_cassettes);

        return new CActiveDataProvider($this, array(
            'criteria' => $criteria,
        ));
    }

    public function behaviors() {
        return array_merge(array(
        ), parent::behaviors());
    }
}