<?php

/**
 * This is the model base class for the table "cassette_details".
 * DO NOT MODIFY THIS FILE! It is automatically generated by AweCrud.
 * If any changes are necessary, you must set or override the required
 * property or method in class "CassetteDetails".
 *
 * Columns in table "cassette_details" available as properties of the model,
 * and there are no model relations.
 *
 * @property integer $id
 * @property integer $cassette_set_no
 * @property integer $cassette_number
 * @property integer $duration
 * @property integer $status
 * @property string $remarks
 *
 */
abstract class BaseCassetteDetails extends AweActiveRecord {

    public static function model($className=__CLASS__) {
        return parent::model($className);
    }

    public function tableName() {
        return 'cassette_details';
    }

    public static function representingColumn() {
        return 'remarks';
    }

    public function rules() {
        return array(
           // array('cassette_set_no, cassette_number, duration, status, remarks', 'required'),
            array('cassette_set_no, cassette_number, duration, status', 'numerical', 'integerOnly'=>true),
            array('remarks', 'length', 'max'=>128),
            array('id, cassette_set_no, cassette_number, duration, status, remarks', 'safe', 'on'=>'search'),
        );
    }

    public function relations() {
        return array(
        );
    }

    /**
     * @return array customized attribute labels (name=>label)
     */
    public function attributeLabels() {
        return array(
                'id' => Yii::t('app', 'ID'),
                'cassette_set_no' => Yii::t('app', 'Cassette Set No'),
                'cassette_number' => Yii::t('app', 'Cassette Number'),
                'duration' => Yii::t('app', 'Duration'),
                'status' => Yii::t('app', 'Status'),
                'remarks' => Yii::t('app', 'Remarks'),
        );
    }

    public function search() {
        $criteria = new CDbCriteria;

        $criteria->compare('id', $this->id);
        $criteria->compare('cassette_set_no', $this->cassette_set_no);
        $criteria->compare('cassette_number', $this->cassette_number);
        $criteria->compare('duration', $this->duration);
        $criteria->compare('status', $this->status);
        $criteria->compare('remarks', $this->remarks, true);

        return new CActiveDataProvider($this, array(
            'criteria' => $criteria,
        ));
    }

    public function behaviors() {
        return array_merge(array(
        ), parent::behaviors());
    }
}