<?php

/**
 * This is the model base class for the table "cassette_handover_details".
 * DO NOT MODIFY THIS FILE! It is automatically generated by AweCrud.
 * If any changes are necessary, you must set or override the required
 * property or method in class "CassetteHandoverDetails".
 *
 * Columns in table "cassette_handover_details" available as properties of the model,
 * and there are no model relations.
 *
 * @property integer $id
 * @property integer $cassete_set_no
 * @property integer $cassette_detail_from_no
 * @property integer $cassete_details_to_number
 * @property integer $user_given_to
 * @property string $out_date
 * @property string $in_date
 * @property integer $given_by
 * @property string $remarks
 * @property string $status
 *
 */
abstract class BaseCassetteHandoverDetails extends AweActiveRecord {

    public static function model($className=__CLASS__) {
        return parent::model($className);
    }

    public function tableName() {
        return 'cassette_handover_details';
    }

    public static function representingColumn() {
        return 'out_date';
    }

    public function rules() {
        return array(
            array('cassete_set_no, cassette_detail_from_no, cassete_details_to_number, user_given_to, given_by', 'required'),
            array('cassete_set_no, cassette_detail_from_no, cassete_details_to_number, user_given_to, given_by', 'numerical', 'integerOnly'=>true),
            array('remarks, status', 'length', 'max'=>128),
            array('out_date, in_date', 'safe'),
            array('out_date, in_date, remarks, status', 'default', 'setOnEmpty' => true, 'value' => null),
            array('id, cassete_set_no, cassette_detail_from_no, cassete_details_to_number, user_given_to, out_date, in_date, given_by, remarks, status', 'safe', 'on'=>'search'),
        );
    }

    public function relations() {
        return array(
        );
    }

    /**
     * @return array customized attribute labels (name=>label)
     */
    public function attributeLabels() {
        return array(
                'id' => Yii::t('app', 'ID'),
                'cassete_set_no' => Yii::t('app', 'Cassete Set No'),
                'cassette_detail_from_no' => Yii::t('app', 'Cassette Detail From No'),
                'cassete_details_to_number' => Yii::t('app', 'Cassete Details To Number'),
                'user_given_to' => Yii::t('app', 'User Given To'),
                'out_date' => Yii::t('app', 'Out Date'),
                'in_date' => Yii::t('app', 'In Date'),
                'given_by' => Yii::t('app', 'Given By'),
                'remarks' => Yii::t('app', 'Remarks'),
                'status' => Yii::t('app', 'Status'),
        );
    }

    public function search() {
        $criteria = new CDbCriteria;

        $criteria->compare('id', $this->id);
        $criteria->compare('cassete_set_no', $this->cassete_set_no);
        $criteria->compare('cassette_detail_from_no', $this->cassette_detail_from_no);
        $criteria->compare('cassete_details_to_number', $this->cassete_details_to_number);
        $criteria->compare('user_given_to', $this->user_given_to);
        $criteria->compare('out_date', $this->out_date, true);
        $criteria->compare('in_date', $this->in_date, true);
        $criteria->compare('given_by', $this->given_by);
        $criteria->compare('remarks', $this->remarks, true);
        $criteria->compare('status', $this->status, true);

        return new CActiveDataProvider($this, array(
            'criteria' => $criteria,
        ));
    }

    public function behaviors() {
        return array_merge(array(
        ), parent::behaviors());
    }
}